# Generated by Django 5.0.6 on 2024-06-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantedtree',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
