# Generated by Django 5.0.6 on 2024-06-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_plantedtree_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantedtree',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
