# Generated by Django 5.0.6 on 2024-06-30 22:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_plantedtree_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantedtree',
            name='register',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plantedtree',
            name='planted_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
